"""platform token, bot_chats

Revision ID: 244ce11d7b37
Revises: ec2a22b6c3e9
Create Date: 2026-10-03 19:42:13.194602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '244ce11d7b37'
down_revision: Union[str, Sequence[str], None] = 'ec2a22b6c3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_chats_bot_id'), 'bot_chats', ['bot_id'], unique=False)
    op.create_index(op.f('ix_bot_chats_chat_id'), 'bot_chats', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_bots_telegram_bot_name'), table_name='bots')
    op.create_index(op.f('ix_bots_telegram_bot_name'), 'bots', ['telegram_bot_name'], unique=False)
    op.drop_column('bots', 'telegram_token_encrypted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('telegram_token_encrypted', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False))
    op.drop_index(op.f('ix_bots_telegram_bot_name'), table_name='bots')
    op.create_index(op.f('ix_bots_telegram_bot_name'), 'bots', ['telegram_bot_name'], unique=True)
    op.drop_index(op.f('ix_bot_chats_chat_id'), table_name='bot_chats')
    op.drop_index(op.f('ix_bot_chats_bot_id'), table_name='bot_chats')
    op.drop_table('bot_chats')
    # ### end Alembic commands ###
