"""init

Revision ID: ec2a22b6c3e9
Revises: 
Create Date: 2026-10-03 19:13:41.816513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2a22b6c3e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('api_key_encrypted', sa.String(length=500), nullable=False),
    sa.Column('telegram_bot_name', sa.String(length=100), nullable=False),
    sa.Column('telegram_token_encrypted', sa.String(length=500), nullable=False),
    sa.Column('telegram_link', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_telegram_bot_name'), 'bots', ['telegram_bot_name'], unique=True)
    op.create_index(op.f('ix_bots_user_id'), 'bots', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_bot_id'), 'messages', ['bot_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_bot_id'), 'uploaded_files', ['bot_id'], unique=False)
    op.create_table('extracted_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('customer_user_id', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'incomplete', 'confirmed', 'shipped', 'completed'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_orders_bot_id'), 'extracted_orders', ['bot_id'], unique=False)
    op.create_index(op.f('ix_extracted_orders_status'), 'extracted_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_orders_status'), table_name='extracted_orders')
    op.drop_index(op.f('ix_extracted_orders_bot_id'), table_name='extracted_orders')
    op.drop_table('extracted_orders')
    op.drop_index(op.f('ix_uploaded_files_bot_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_bot_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_bots_user_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_telegram_bot_name'), table_name='bots')
    op.drop_table('bots')
    op.drop_table('users')
    # ### end Alembic commands ###
